### ISSUE TITLE
"Expression Types" documentation missing

### ISSUE THREAD

**Issue by wraugh** [awwright/uri-template-router#1]
[The "Expression Types" section of the Readme](https://github.com/awwright/uri-template-router#expression-types) is the same as the above section ([Resume Search](https://github.com/awwright/uri-template-router#resume-search)). Looks like a copy-paste mishap.

**Comment by awwright** [comment]
Ah, nice catch!

Honestly I'm not sure what's supposed to go there at first glance, I wrote the "Features" section all at the same time.

**Comment by awwright** [comment]
Fixed in 2b6a3e7589e3de7d2cf3e9bd4fd5c9bb5968243b
