### ISSUE TITLE
[Improvement] Store routes as a Map

### ISSUE THREAD

**Issue by Lcfvs** [awwright/uri-template-router#2]
Hi,

To easily get a route by its name, it seems better to use a Map, it isn't?

**Comment by awwright** [comment]
I don't see why not.

I'm curious, is there a specific advantage you're looking for? Or is it just a better practice?

**Comment by Lcfvs** [comment]
Hi,

It's only more agnostic, we don't need to check your own logic to be able to get a route by its name (or check existence),  every JS dev already know le Map logic.

```js
router.has(name)
router.get(name)
```

**Comment by awwright** [comment]
@Lcfvs Can you give me a code sample of how you'd use it?

**Comment by Lcfvs** [comment]
@awwright Sure

Based on your examples, I have these modules:

`router.js`
```js
const router = new Router;
 
router.addTemplate('http://example.com/', {}, 'index');
router.addTemplate('http://example.com/q{n}.html', {}, 'page_html');
router.addTemplate('http://example.com/q{n}.txt', {}, 'page_txt');
router.addTemplate('http://example.com/blog{/y,m,d,slug}', {}, 'blog_post');
router.addTemplate('http://example.com{/path*}', {}, 'path');

export default router;
```

`server.js`
```js
import router from './router.js';

const server = new Server;
 
server.onRoute(router.routes.get('index'), () => {
  // do something to respond
})
 
server.onRoute(router.routes.get('page_html'), () => {
  // do something to respond
})
 
//...
export default server
```

`index.js`
```js
import router from './router.js';
import { attributes, children, value } from './dom/nodes.js';
import { html } from './dom/markups.js';
import text from './dom/nodes/text.js';

const { attributes: { href }, elements: { a }} = html.attributes

export default () => {
  return a
     [attributes]([
       href[value](router.routes.get('index').gen())
     ])
     [children]([
        text[value]('return to the index')
     ])
}
```

**Comment by awwright** [comment]
Thanks @Lcfvs 

I'll probably have some more questions later.

And I am AAA_awright on Freenode

**Comment by awwright** [comment]
Hi @Lcfvs, I hope you've been able to work out a solution for what you were working on. Has this library been of use at all?

The library doesn't have a concept of "naming" a route: the key for the route is the URI Template itself. There's an associated `matchValue` property, but it can be any value (I store objects in there). I suppose that doesn't pose a problem for a Map, but that still seems awkward to me.

I figure you can do something [like this](https://awwright.github.io/uri-template-router/usage.xhtml):

```javascript
const router = new Router;
const routes = {
	blog: router.addRoute('http://localhost/blog{/yyyy,mm,dd,slug}'),
	page: router.addRoute('http://localhost{/page}'),
	file: router.addRoute('http://localhost/static{/path}'),
	png: router.addRoute('http://localhost/static{/path}.png'),
	css: router.addRoute('http://localhost/static{/path}.css'),
	js: router.addRoute('http://localhost/static{/path}.js'),
};

router.resolveURI('http://localhost/blog/1999/10/30/homesteading-the-noosphere');

routes.blog.toString({ yyyy:'1999', mm:'10', dd:'30', slug:'homesteading-the-noosphere' });
```

Is this something that works for you, or do you still need routes to have an associated name too?

(I'll still see about implementing this, seeing as using an object as a key is not a problem for `Map`).

**Comment by Lcfvs** [comment]
Yeah, you're right, a Map risks to make some collisions, since the matchValue can be anything used by another route.

Thanks and sorry for that.

**Comment by awwright** [comment]
@Lcfvs Nothing to apologize for! Actually, I implemented a `getValue` function. The one caveat is if you try to change the associated `matchValue`, or if you insert a second Route with a duplicate `matchValue`, it won't do anything.
