### ISSUE TITLE
[Improvement] Module type

### ISSUE THREAD

**Issue by Lcfvs** [awwright/uri-template-router#3]
Hi again,

Since a router can be used both in front/back, it can be useful to use it as a ES6 module, preferably without any package bundling requirement.

Any chance to make it as an ES6 module?

**Comment by awwright** [comment]
@Lcfvs Is that well supported by Web browsers and Node.js these days? I'm really not sure what the advantage is over e.g. Browserify

**Comment by Lcfvs** [comment]
@awwright 
node.js@13.2.0 already supports the ES modules
For the browsers: https://caniuse.com/#search=module

Browserify, Webpack, Parcel & others are fine, but the it's a few boring to be forced to use them where the modern features provide a way to load our resources without that extra process.

**Comment by awwright** [comment]
Afaict Node v22.4.0 still doesn't support ES modules:

> SyntaxError: Cannot use import statement outside a module

and

> SyntaxError: Unexpected token 'export'

So this still requires a feature flag of some sort

**Comment by Lcfvs** [comment]
> So this still requires a feature flag of some sort
Just the `"type": "module"` into your `package.json` ;)
