### ISSUE TITLE
Please Provide License Terms

### ISSUE THREAD

**Issue by cjaccino** [awwright/uri-template-router#5]
This is a valuable piece of software.  If you would like projects to use it, please provide licensing terms.

**Comment by awwright** [comment]
@cjaccino This is public domain software. I added an UNLICENSE declaration to the repository to make this more explicit.

Note, it was listed in package.json as such; and I think any statement like that is both sufficient for legal purposes and applies retroactively.

**Comment by cjaccino** [comment]
Missed it in the package.json.  Thanks for making the update!

**Comment by awwright** [comment]
@cjaccino And if you have any feedback or want to describe your uses, please feel free to do so. Thanks!
